version: '3.9'

services:

  app:
    build:
      context: ./docker-app
      target: webserver_test
    environment:
      # run flush, migrate and collectstatic in entrypoint
      DEBUG: 1
      # we must use the same db for test and runserver
      SQL_DATABASE: test_${POSTGRES_DB}
      SQL_DATABASE_TEST: test_${POSTGRES_DB}

  worker_wrapper:
    environment:
      # we must use the same db for test and runserver
      SQL_DATABASE: test_${POSTGRES_DB}
      SQL_DATABASE_TEST: test_${POSTGRES_DB}
    scale: ${QFIELDCLOUD_WORKER_REPLICAS}

  db:
    environment:
      POSTGRES_DB: test_${POSTGRES_DB}

networks:
  default:
    # Use a custom driver
    name: ${QFIELDCLOUD_DEFAULT_NETWORK}

volumes:
  # We use a different volume, just so that the test_ database
  # gets created in the entrypoint.
  postgres_data:
    name: qfieldcloud_postgres_data_test
